title: "Resource Awareness in Programming: Algebra, Rewriting, and Analysis"
author: "Gabriele Lobbia"
# logo: /assets/bojack_hopper.png
#description: "gabriele[dot]lobbia[at]unibo[dot]it"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Dependencies
#markdown:         redcarpet
#highlighter:      pygments

# Layout

show_excerpts: false       # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: Home, file: "index.md"}
  - {title: Kick-off Meeting, file: "kickoff.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  #- {title: Mail, icon: envelope, url: "mailto:lobbia@math.muni.cz"}
  #- {title: Muni page, icon: university, url: "https://www.muni.cz/en/people/247277-gabriele-lobbia"}
  #- {title: ORCID, icon: orcid, url: "https://orcid.org/0000-0002-2732-0317"}
  #- {title: Scholar, icon: user-graduate, url: "https://scholar.google.com/citations?user=xjHu2moAAAAJ&hl=it"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
